import os

COLLISION_MIN_IMPACT = float(os.getenv("COLLISION_MIN_IMPACT", "3.0"))
COLLISION_MIN_REL_SPEED = float(os.getenv("COLLISION_MIN_REL_SPEED", "8.0"))
COLLISION_MIN_COMBINED_SPEED_KMH = float(os.getenv("COLLISION_MIN_COMBINED_SPEED_KMH", "45.0"))
COLLISION_POINT_COOLDOWN_SEC = float(os.getenv("COLLISION_POINT_COOLDOWN_SEC", "1.5"))
BRAKE_CHECK_DELTA_KMH = float(os.getenv("BRAKE_CHECK_DELTA_KMH", "8.0"))
BRAKE_CHECK_MIN_IMPACT = float(os.getenv("BRAKE_CHECK_MIN_IMPACT", "10"))
BRAKE_CHECK_LOW_SPEED_KMH = float(os.getenv("BRAKE_CHECK_LOW_SPEED_KMH", "22.0"))

MAX_BATTLE_GAP_METERS = float(os.getenv("MAX_BATTLE_GAP_METERS", "45.0"))
PAIR_LOCK_MAX_DISTANCE_METERS = float(os.getenv("PAIR_LOCK_MAX_DISTANCE_METERS", "20.0"))
PAIR_LOCK_MIN_SPEED_KMH = float(os.getenv("PAIR_LOCK_MIN_SPEED_KMH", "35.0"))

FINISH_POINT_MIN_GAP_METERS = float(os.getenv("BATTLE_FINISH_POINT_MIN_GAP_METERS", "50.0"))
DISAPPEAR_GAP_METERS = float(os.getenv("BATTLE_DISAPPEAR_GAP_METERS", "250.0"))
DEFAULT_WIN_MIN_POINTS = int(os.getenv("BATTLE_DEFAULT_WIN_MIN_POINTS", "2"))

OVERTAKE_POINT_COOLDOWN_SEC = float(os.getenv("OVERTAKE_POINT_COOLDOWN_SEC", "2.0"))
OVERTAKE_MIN_GAP_METERS = float(os.getenv("OVERTAKE_MIN_GAP_METERS", "15.0"))
OVERTAKE_MARGIN_SPLINE = float(os.getenv("BATTLE_OVERTAKE_MARGIN_SPLINE", "0.005"))

COLLISION_WARN_COOLDOWN_SEC = float(os.getenv("BATTLE_COLLISION_WARN_COOLDOWN_SEC", "4.0"))

PAIR_STICKY_TIMEOUT_SEC = float(os.getenv("BATTLE_PAIR_STICKY_TIMEOUT_SEC", "20.0"))
ROLE_ASSIGN_MIN_GAP_SPLINE = float(os.getenv("BATTLE_ROLE_ASSIGN_MIN_GAP_SPLINE", "0.0006"))
ROLE_ASSIGN_WAIT_SEC = float(os.getenv("BATTLE_ROLE_ASSIGN_WAIT_SEC", "6.0"))
WRONG_POSITION_CHECK_WINDOW_SEC = float(os.getenv("BATTLE_WRONG_POSITION_CHECK_WINDOW_SEC", "3.0"))
WRONG_POSITION_MARGIN_SPLINE = float(os.getenv("BATTLE_WRONG_POSITION_MARGIN_SPLINE", "0.0006"))
PRESTART_GAP_ABORT_GRACE_SEC = float(os.getenv("BATTLE_PRESTART_GAP_ABORT_GRACE_SEC", "2.0"))
GAP_ABORT_MIN_BOTH_SPEED_KMH = float(os.getenv("BATTLE_GAP_ABORT_MIN_BOTH_SPEED_KMH", "20.0"))
